version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://it22366122:it22366122@ds-foodordering.wqymxo5.mongodb.net/?retryWrites=true&w=majority&appName=ds-foodOrdering
      - JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
      - JWT_EXPIRATION=1d
    networks:
      - microservices-network

  payment-service:
    build: ./payment-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb+srv://admin:admin1234@cluster0.tayveae.mongodb.net/food_delivery_payment_db?retryWrites=true&w=majority
      - JWT_SECRET=35bdba807fbd504850d82daaa1cd4d920ddec97ee33a52f4c9ceac29aa5f2095
      - PAYHERE_MERCHANT_ID=1230287
      - PAYHERE_SECRET=MTg5OTM5ODQ1MTM4NjMyMzg1MTcyNDc0Njg3ODMyNDUxNDk3NjYz
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - microservices-network
    volumes:
      - ./payment-service:/usr/src/app
      - /usr/src/app/node_modules

networks:
  microservices-network:
    driver: bridge

volumes:
  mongo-data:
